name: CI-CD Desafio

on: 
  push: 
    branches: ["main"]

jobs: 
  CI:  
    runs-on: ubuntu-latest

    steps: 
      # Checkout do código
      - uses: actions/checkout@v3

      # Autenticação no DockerHub
      - name: Autenticacao do DockerHub
        uses: docker/login-action@v3.3.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construção e push da imagem Docker
      - name: Construcao da imagem Docker
        uses: docker/build-push-action@v3
        with: 
          context: ./src  
          file: ./src/Dockerfile
          push: true
          tags: |
            vicctorsds/desafio-kube-cicd:${{ github.run_id }}
            vicctorsds/desafio-kube-cicd:latest

    CD:   
      runs-on: ubuntu-latest
      needs: [CI]
      steps:  
         # Checkout do código
        - uses: actions/checkout@v3

        # Setando o K8S
        - name: Definindo o context
          uses: Azure/k8s-set-context@v3.0
           with: 
            method: kubeconfig
            kubeconfig: ${{secrets.K8S_CONFIG}}
          
