name: CI-CD Desafio

on: 
  push: 
    branches: ["main"]

jobs: 
  CI:  
    runs-on: ubuntu-latest

    steps: 
      # Checkout do código
      - uses: actions/checkout@v3
      
      # Construção e push da imagem Docker
      - name: Construcao da imagem Docker
        uses: docker/build-push-action@v3
        with: 
          context: ./src  
          file: ./src/Dockerfile
          push: true
          tags: |
            vicctorsds/desafio-kube-cicd:v1
            vicctorsds/desafio-kube-cicd:latest
