name: CI-CD Desafio

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Autenticação no DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construção e push da imagem Docker
        uses: docker/build-push-action@v3
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            vicctorsds/desafio-kube-cicd:${{ github.run_id }}
            vicctorsds/desafio-kube-cicd:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # Instalar o eksctl
      - name: Instalar o eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.106.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      # Atualizar kubeconfig para o EKS
      - name: Update kubeconfig for EKS using eksctl
        run: eksctl utils write-kubeconfig --region ${{ secrets.AWS_REGION }} --name desafio-loomi

      - name: Verificar Configuração do Kubectl
        run: kubectl config view

      - name: Descrever o Deployment web
        run: kubectl describe deployment web --namespace default

      - name: Esperar pelo Rollout do Deployment
        run: kubectl rollout status deployment/web --namespace default --timeout=10m

      - name: Verificar os Logs da Pod
        run: |
          POD_NAME=$(kubectl get pods --namespace default -l app=web -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME --namespace default
